export type Language = 'en' | 'es' | 'fr' | 'de' | 'pt';

export type ToolId =
  | 'compress'
  | 'merge'
  | 'split'
  | 'img2pdf'
  | 'pdf2img'
  | 'imgconv'
  | 'watermark'
  | 'pagenum'
  | 'rotate'
  | 'pdf2word'
  | 'word2pdf';

export interface Tool {
  id: ToolId;
  letter: string;
  nameKey: string; // Key in translations for localized name
  descKey: string; // Key in translations for localized desc
  live: boolean;
  accept?: string;
  multi?: boolean;
}

export const TOOLS: Tool[] = [
  { id: 'compress', letter: 'C', nameKey: 'tool_compress_name', descKey: 'tool_compress_desc', live: true, accept: '.pdf', multi: false },
  { id: 'merge', letter: 'M', nameKey: 'tool_merge_name', descKey: 'tool_merge_desc', live: true, accept: '.pdf', multi: true },
  { id: 'split', letter: 'S', nameKey: 'tool_split_name', descKey: 'tool_split_desc', live: true, accept: '.pdf', multi: false },
  { id: 'img2pdf', letter: 'I', nameKey: 'tool_img2pdf_name', descKey: 'tool_img2pdf_desc', live: true, accept: '.jpg,.jpeg,.png', multi: true },
  { id: 'pdf2img', letter: 'P', nameKey: 'tool_pdf2img_name', descKey: 'tool_pdf2img_desc', live: true, accept: '.pdf', multi: false },
  { id: 'imgconv', letter: 'I', nameKey: 'tool_imgconv_name', descKey: 'tool_imgconv_desc', live: true, accept: '.jpg,.jpeg,.png,.webp', multi: false },
  { id: 'watermark', letter: 'W', nameKey: 'tool_watermark_name', descKey: 'tool_watermark_desc', live: true, accept: '.pdf', multi: false },
  { id: 'pagenum', letter: '#', nameKey: 'tool_pagenum_name', descKey: 'tool_pagenum_desc', live: true, accept: '.pdf', multi: false },
  { id: 'rotate', letter: 'R', nameKey: 'tool_rotate_name', descKey: 'tool_rotate_desc', live: true, accept: '.pdf', multi: false },
  { id: 'pdf2word', letter: 'P', nameKey: 'tool_pdf2word_name', descKey: 'tool_pdf2word_desc', live: false },
  { id: 'word2pdf', letter: 'W', nameKey: 'tool_word2pdf_name', descKey: 'tool_word2pdf_desc', live: false }
];

export const LANG_NAMES: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  pt: 'Português'
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    nav_tools: 'Tools',
    nav_pricing: 'Pricing',
    nav_privacy: 'Privacy',
    nav_browse: 'Browse tools',
    hero_eyebrow: '9 tools live · fully client-side · verified working',
    hero_h1: 'PDF and image tools that <span class="text-brass">actually run</span> in your browser.',
    hero_p: 'Compress, merge, split, rotate, watermark, and convert — processed entirely on your device using real browser libraries. No uploads. No accounts required to try it.',
    cta_browse: 'Browse all tools',
    cta_pricing: 'See pricing',
    fact_1: 'tools live & verified',
    fact_2: 'files ever leave your device',
    fact_3: 'tools coming soon',
    honesty_title: 'Honest status note:',
    honesty_body: 'every tool marked "Live" below uses a real client-side library (pdf-lib, pdf.js, canvas) and was checked against that library\'s actual API before being built — not assumed. PDF↔Word need server-side processing we haven\'t built, and PDF password protection isn\'t reliably possible with the libraries this site uses — both are marked Coming Soon rather than faked.',
    tools_eyebrow: 'Available tools',
    tools_h2: 'All 9 tools',
    tools_p: 'Pick a tool to get started. Live tools process your file right here, right now.',
    pricing_eyebrow: 'Pricing',
    pricing_h2: 'Simple pricing',
    pricing_p: "Start free. Premium billing isn't wired up yet, so we're not charging anyone until it is.",
    price_free_tier: 'FREE',
    price_free_1: 'All 9 live tools, unlimited use',
    price_free_2: 'Genuinely client-side processing',
    price_free_3: 'No signup required',
    price_free_4: 'No file size games — browser memory is the only limit',
    price_free_btn: 'Start using tools',
    price_premium_tier: 'PREMIUM',
    price_premium_1: 'Batch / folder processing',
    price_premium_2: 'Drag-to-reorder queues',
    price_premium_3: 'ZIP download of results',
    price_premium_4: 'Priority support',
    price_premium_btn: 'Coming soon — billing not built yet',
    privacy_eyebrow: 'Privacy',
    privacy_h2: 'What actually happens to your files',
    privacy_p1: 'Compress PDF, Merge PDF, Split PDF, Image to PDF, PDF to Image, Image Converter, Watermark PDF, Add Page Numbers, and Rotate PDF — these 9 tools run entirely in your browser using open-source libraries (pdf-lib, pdf.js, and the browser\'s own Canvas API). Your file is read into browser memory, processed, and the result is offered back to you as a download. It is never transmitted anywhere. You can verify this yourself by opening your browser\'s network tab while using any of these tools.',
    privacy_p2: 'PDF to Word and Word to PDF are not live yet. These conversions typically require server-side processing to work reliably, and we haven\'t built or deployed that backend. We\'re not offering a fake or broken version of these tools in the meantime.',
    privacy_p3: 'This page currently has no accounts, no database, and no tracking — it\'s a static tool page. If accounts or a premium tier are added later, this policy will be rewritten to accurately describe whatever real data is collected at that time, not before.',
    footer_tagline: 'Fast PDF and image tools that respect your files — and tell you the truth about what\'s real.',
    footer_product: 'Product',
    footer_alltools: 'All tools',
    footer_pricing: 'Pricing',
    footer_company: 'Company',
    footer_privacy: 'Privacy',
    footer_copy: '© 2026 DocuFlowPlus. Built honestly, tool by tool.',
    // Tool Names and Descs
    tool_compress_name: 'Compress PDF',
    tool_compress_desc: 'Reduce PDF file size by optimizing internal structure.',
    tool_merge_name: 'Merge PDF',
    tool_merge_desc: 'Combine multiple PDFs into a single document.',
    tool_split_name: 'Split PDF',
    tool_split_desc: 'Extract every page of a PDF into separate files, zipped.',
    tool_img2pdf_name: 'Image to PDF',
    tool_img2pdf_desc: 'Combine one or more images into a single PDF.',
    tool_pdf2img_name: 'PDF to Image',
    tool_pdf2img_desc: 'Convert each PDF page into a PNG image.',
    tool_imgconv_name: 'Image Converter',
    tool_imgconv_desc: 'Convert between PNG, JPG, and WEBP formats.',
    tool_watermark_name: 'Watermark PDF',
    tool_watermark_desc: 'Stamp diagonal text across every page.',
    tool_pagenum_name: 'Add Page Numbers',
    tool_pagenum_desc: 'Add page numbers to the bottom of every page.',
    tool_rotate_name: 'Rotate PDF',
    tool_rotate_desc: 'Rotate every page in a PDF by 90, 180, or 270 degrees.',
    tool_pdf2word_name: 'PDF to Word',
    tool_pdf2word_desc: 'Extract PDF text into an editable Word document.',
    tool_word2pdf_name: 'Word to PDF',
    tool_word2pdf_desc: 'Convert .docx files into PDF format.'
  },
  es: {
    nav_tools: 'Herramientas',
    nav_pricing: 'Precios',
    nav_privacy: 'Privacidad',
    nav_browse: 'Ver herramientas',
    hero_eyebrow: '9 herramientas activas · 100% en tu navegador · verificadas',
    hero_h1: 'Herramientas de PDF e imagen que <span class="text-brass">realmente funcionan</span> en tu navegador.',
    hero_p: 'Comprime, une, divide, rota, marca con agua y convierte — todo procesado en tu propio dispositivo con librerías reales de navegador. Sin subidas. Sin cuenta necesaria para probarlo.',
    cta_browse: 'Ver todas las herramientas',
    cta_pricing: 'Ver precios',
    fact_1: 'herramientas activas y verificadas',
    fact_2: 'archivos que salen de tu dispositivo',
    fact_3: 'herramientas próximamente',
    honesty_title: 'Nota de estado honesta:',
    honesty_body: 'cada herramienta marcada como "Activa" usa una librería real del lado del cliente (pdf-lib, pdf.js, canvas) y fue verificada contra la API real de esa librería antes de construirla — no se asumió. PDF↔Word necesitan procesamiento en servidor que aún no hemos construido, y la protección con contraseña de PDF no es posible de forma fiable con las librerías que usa este sitio — ambas están marcadas como "Próximamente" en lugar de simularse.',
    tools_eyebrow: 'Herramientas disponibles',
    tools_h2: 'Las 9 herramientas',
    tools_p: 'Elige una herramienta para empezar. Las herramientas activas procesan tu archivo aquí mismo, ahora mismo.',
    pricing_eyebrow: 'Precios',
    pricing_h2: 'Precios sencillos',
    pricing_p: 'Empieza gratis. La facturación Premium aún no está activa, así que no cobramos a nadie todavía.',
    price_free_tier: 'GRATIS',
    price_free_1: 'Las 9 herramientas activas, uso ilimitado',
    price_free_2: 'Procesamiento genuinamente local',
    price_free_3: 'No requiere registro',
    price_free_4: 'Sin trucos de tamaño de archivo — solo el límite de memoria de tu navegador',
    price_free_btn: 'Empezar a usar las herramientas',
    price_premium_tier: 'PREMIUM',
    price_premium_1: 'Procesamiento por lotes / carpetas',
    price_premium_2: 'Reordenar arrastrando',
    price_premium_3: 'Descarga de resultados en ZIP',
    price_premium_4: 'Soporte prioritario',
    price_premium_btn: 'Próximamente — facturación aún no implementada',
    privacy_eyebrow: 'Privacidad',
    privacy_h2: 'Qué pasa realmente con tus archivos',
    privacy_p1: 'Comprimir PDF, Unir PDF, Dividir PDF, Imagen a PDF, PDF a Imagen, Conversor de Imagen, Marca de Agua, Numeración de Páginas y Rotar PDF — estas 9 herramientas funcionan completamente en tu navegador usando librerías de código abierto (pdf-lib, pdf.js y la API Canvas del propio navegador). Tu archivo se carga en la memoria del navegador, se procesa, y el resultado se te ofrece como descarga. Nunca se transmite a ningún sitio. Puedes comprobarlo tú mismo abriendo la pestaña de red de tu navegador mientras usas cualquiera de estas herramientas.',
    privacy_p2: 'PDF a Word y Word a PDF aún no están activas. Estas conversiones normalmente requieren procesamiento en servidor para funcionar de forma fiable, y todavía no hemos construido ni desplegado ese backend. No ofrecemos una versión falsa o rota de estas herramientas mientras tanto.',
    privacy_p3: 'Esta página actualmente no tiene cuentas, ni base de datos, ni seguimiento — es una página de herramientas estática. Si más adelante se añaden cuentas o un nivel premium, esta política se reescribirá para describir con precisión los datos reales que se recojan en ese momento, no antes.',
    footer_tagline: 'Herramientas rápidas de PDF e imagen que respetan tus archivos — y te dicen la verdad sobre lo que es real.',
    footer_product: 'Producto',
    footer_alltools: 'Todas las herramientas',
    footer_pricing: 'Precios',
    footer_company: 'Empresa',
    footer_privacy: 'Privacidad',
    footer_copy: '© 2026 DocuFlowPlus. Construido con honestidad, herramienta por herramienta.',
    // Tool Names and Descs
    tool_compress_name: 'Comprimir PDF',
    tool_compress_desc: 'Reduce el tamaño del PDF optimizando su estructura interna.',
    tool_merge_name: 'Unir PDF',
    tool_merge_desc: 'Combina múltiples archivos PDF en un único documento.',
    tool_split_name: 'Dividir PDF',
    tool_split_desc: 'Extrae cada página de un PDF en archivos individuales en un ZIP.',
    tool_img2pdf_name: 'Imagen a PDF',
    tool_img2pdf_desc: 'Combina una o más imágenes en un solo archivo PDF.',
    tool_pdf2img_name: 'PDF a Imagen',
    tool_pdf2img_desc: 'Convierte cada página de un PDF en una imagen PNG.',
    tool_imgconv_name: 'Conversor de Imagen',
    tool_imgconv_desc: 'Convierte imágenes entre formatos PNG, JPG y WEBP.',
    tool_watermark_name: 'Marca de Agua',
    tool_watermark_desc: 'Añade un texto diagonal de marca de agua en cada página.',
    tool_pagenum_name: 'Numeración de Páginas',
    tool_pagenum_desc: 'Añade números de página en la parte inferior de cada página.',
    tool_rotate_name: 'Rotar PDF',
    tool_rotate_desc: 'Rota todas las páginas de un PDF en 90, 180 o 270 grados.',
    tool_pdf2word_name: 'PDF a Word',
    tool_pdf2word_desc: 'Extrae el texto del PDF a un documento Word editable.',
    tool_word2pdf_name: 'Word a PDF',
    tool_word2pdf_desc: 'Convierte archivos .docx a formato PDF.'
  },
  fr: {
    nav_tools: 'Outils',
    nav_pricing: 'Tarifs',
    nav_privacy: 'Confidentialité',
    nav_browse: 'Voir les outils',
    hero_eyebrow: '9 outils actifs · 100 % dans votre navigateur · vérifiés',
    hero_h1: 'Des outils PDF et image qui <span class="text-brass">fonctionnent vraiment</span> dans votre navigateur.',
    hero_p: "Compressez, fusionnez, divisez, pivotez, filigranez et convertissez — tout est traité entièrement sur votre appareil grâce à de vraies bibliothèques de navigateur. Aucun envoi. Aucun compte requis pour essayer.",
    cta_browse: 'Voir tous les outils',
    cta_pricing: 'Voir les tarifs',
    fact_1: 'outils actifs et vérifiés',
    fact_2: 'fichiers qui quittent votre appareil',
    fact_3: 'outils à venir',
    honesty_title: 'Note de statut honnête :',
    honesty_body: 'chaque outil marqué « Actif » ci-dessous utilise une véritable bibliothèque côté client (pdf-lib, pdf.js, canvas) et a été vérifié par rapport à l\'API réelle de cette bibliothèque avant d\'être construit — jamais supposé. PDF↔Word nécessitent un traitement côté serveur que nous n\'avons pas encore construit, et la protection par mot de passe des PDF n\'est pas réalisable de façon fiable avec les bibliothèques utilisées ici — les deux sont marqués « Bientôt disponible » plutôt que simulés.',
    tools_eyebrow: 'Outils disponibles',
    tools_h2: 'Les 9 outils',
    tools_p: 'Choisissez un outil pour commencer. Les outils actifs traitent votre fichier ici même, tout de suite.',
    pricing_eyebrow: 'Tarifs',
    pricing_h2: 'Des tarifs simples',
    pricing_p: "Commencez gratuitement. La facturation Premium n'est pas encore en place, donc personne n'est facturé pour l'instant.",
    price_free_tier: 'GRATUIT',
    price_free_1: 'Les 9 outils actifs, usage illimité',
    price_free_2: 'Traitement réellement côté client',
    price_free_3: 'Aucune inscription requise',
    price_free_4: "Pas de limites artificielles de taille — seule la mémoire de votre navigateur compte",
    price_free_btn: 'Commencer à utiliser les outils',
    price_premium_tier: 'PREMIUM',
    price_premium_1: 'Traitement par lot / dossier',
    price_premium_2: 'Réorganisation par glisser-déposer',
    price_premium_3: 'Téléchargement des résultats en ZIP',
    price_premium_4: 'Support prioritaire',
    price_premium_btn: 'Bientôt disponible — facturation non encore mise en place',
    privacy_eyebrow: 'Confidentialité',
    privacy_h2: 'Ce qui arrive réellement à vos fichiers',
    privacy_p1: "Compresser PDF, Fusionner PDF, Diviser PDF, Image vers PDF, PDF vers Image, Convertisseur d'image, Filigrane PDF, Numérotation des pages et Pivoter PDF — ces 9 outils fonctionnent entièrement dans votre navigateur grâce à des bibliothèques open-source (pdf-lib, pdf.js et l'API Canvas du navigateur lui-même). Votre fichier est chargé en mémoire du navigateur, traité, puis le résultat vous est proposé en téléchargement. Il n'est jamais transmis ailleurs. Vous pouvez le vérifier vous-même en ouvrant l'onglet réseau de votre navigateur pendant l'utilisation de ces outils.",
    privacy_p2: "PDF vers Word et Word vers PDF ne sont pas encore actifs. Ces conversions nécessitent généralement un traitement côté serveur pour fonctionner de manière fiable, et nous n'avons pas encore construit ni déployé ce backend. Nous ne proposons pas de version fausse ou défectueuse de ces outils en attendant.",
    privacy_p3: "Cette page ne comporte actuellement aucun compte, aucune base de données et aucun suivi — c'est une page d'outils statique. Si des comptes ou un niveau premium sont ajoutés plus tard, cette politique sera réécrite pour décrire fidèlement les données réellement collectées à ce moment-là, pas avant.",
    footer_tagline: 'Des outils PDF et image rapides qui respectent vos fichiers — et qui vous disent la vérité sur ce qui est réel.',
    footer_product: 'Produit',
    footer_alltools: 'Tous les outils',
    footer_pricing: 'Tarifs',
    footer_company: 'Entreprise',
    footer_privacy: 'Confidentialité',
    footer_copy: '© 2026 DocuFlowPlus. Construit honnêtement, outil par outil.',
    // Tool Names and Descs
    tool_compress_name: 'Compresser PDF',
    tool_compress_desc: 'Réduire la taille du PDF en optimisant sa structure interne.',
    tool_merge_name: 'Fusionner PDF',
    tool_merge_desc: 'Combiner plusieurs fichiers PDF en un seul document.',
    tool_split_name: 'Diviser PDF',
    tool_split_desc: 'Extraire chaque page d\'un PDF en fichiers individuels dans un ZIP.',
    tool_img2pdf_name: 'Image vers PDF',
    tool_img2pdf_desc: 'Combiner une ou plusieurs images en un seul fichier PDF.',
    tool_pdf2img_name: 'PDF vers Image',
    tool_pdf2img_desc: 'Convertir chaque page d\'un PDF en image PNG.',
    tool_imgconv_name: 'Convertisseur d\'image',
    tool_imgconv_desc: 'Convertir des images entre les formats PNG, JPG et WEBP.',
    tool_watermark_name: 'Filigrane PDF',
    tool_watermark_desc: 'Ajouter un texte en filigrane diagonal sur chaque page.',
    tool_pagenum_name: 'Numérotation des pages',
    tool_pagenum_desc: 'Ajouter des numéros de page au bas de chaque page.',
    tool_rotate_name: 'Pivoter PDF',
    tool_rotate_desc: 'Faire pivoter toutes les pages d\'un PDF de 90, 180 ou 270 degrés.',
    tool_pdf2word_name: 'PDF vers Word',
    tool_pdf2word_desc: 'Extraire le texte du PDF dans un document Word modifiable.',
    tool_word2pdf_name: 'Word vers PDF',
    tool_word2pdf_desc: 'Convertir des fichiers .docx au format PDF.'
  },
  de: {
    nav_tools: 'Werkzeuge',
    nav_pricing: 'Preise',
    nav_privacy: 'Datenschutz',
    nav_browse: 'Werkzeuge ansehen',
    hero_eyebrow: '9 Tools live · vollständig im Browser · verifiziert',
    hero_h1: 'PDF- und Bildwerkzeuge, die <span class="text-brass">wirklich funktionieren</span> — direkt in Ihrem Browser.',
    hero_p: 'Komprimieren, zusammenführen, teilen, drehen, mit Wasserzeichen versehen und konvertieren — alles vollständig auf Ihrem Gerät mit echten Browser-Bibliotheken verarbeitet. Kein Upload. Kein Konto zum Ausprobieren nötig.',
    cta_browse: 'Alle Werkzeuge ansehen',
    cta_pricing: 'Preise ansehen',
    fact_1: 'Tools live & verifiziert',
    fact_2: 'Dateien verlassen je Ihr Gerät',
    fact_3: 'Tools in Vorbereitung',
    honesty_title: 'Ehrlicher Statushinweis:',
    honesty_body: 'jedes unten als „Live" markierte Tool nutzt eine echte clientseitige Bibliothek (pdf-lib, pdf.js, canvas) und wurde vor der Umsetzung gegen die tatsächliche API dieser Bibliothek geprüft — nicht einfach angenommen. PDF↔Word benötigen serverseitige Verarbeitung, die wir noch nicht gebaut haben, und PDF-Passwortschutz ist mit den hier verwendeten Bibliotheken nicht zuverlässig möglich — beide sind ehrlich als „Bald verfügbar" statt vorgetäuscht markiert.',
    tools_eyebrow: 'Verfügbare Werkzeuge',
    tools_h2: 'Alle 9 Werkzeuge',
    tools_p: 'Wählen Sie ein Werkzeug, um zu starten. Live-Tools verarbeiten Ihre Datei direkt hier, sofort.',
    pricing_eyebrow: 'Preise',
    pricing_h2: 'Einfache Preise',
    pricing_p: 'Kostenlos starten. Die Premium-Abrechnung ist noch nicht eingerichtet, daher wird derzeit niemandem etwas berechnet.',
    price_free_tier: 'KOSTENLOS',
    price_free_1: 'Alle 9 Live-Tools, unbegrenzte Nutzung',
    price_free_2: 'Wirklich clientseitige Verarbeitung',
    price_free_3: 'Keine Anmeldung erforderlich',
    price_free_4: 'Keine künstlichen Größenlimits — nur der Arbeitsspeicher Ihres Browsers zählt',
    price_free_btn: 'Werkzeuge jetzt nutzen',
    price_premium_tier: 'PREMIUM',
    price_premium_1: 'Stapel-/Ordnerverarbeitung',
    price_premium_2: 'Reihenfolge per Drag & Drop ändern',
    price_premium_3: 'Ergebnisse als ZIP herunterladen',
    price_premium_4: 'Priorisierter Support',
    price_premium_btn: 'Bald verfügbar — Abrechnung noch nicht eingerichtet',
    privacy_eyebrow: 'Datenschutz',
    privacy_h2: 'Was mit Ihren Dateien wirklich passiert',
    privacy_p1: 'PDF komprimieren, PDF zusammenführen, PDF teilen, Bild zu PDF, PDF zu Bild, Bildkonverter, PDF Wasserzeichen, Seitenzahlen und PDF drehen — diese 9 Tools laufen vollständig in Ihrem Browser mit Open-Source-Bibliotheken (pdf-lib, pdf.js und der browsereigenen Canvas-API). Ihre Datei wird in den Browser-Speicher geladen, verarbeitet, und das Ergebnis wird Ihnen zum Download angeboten. Sie wird niemals irgendwohin übertragen. Sie können dies selbst überprüfen, indem Sie den Netzwerk-Tab Ihres Browsers während der Nutzung dieser Tools öffnen.',
    privacy_p2: 'PDF zu Word und Word zu PDF sind noch nicht live. Diese Konvertierungen erfordern in der Regel eine serverseitige Verarbeitung, um zuverlässig zu funktionieren, und wir haben dieses Backend noch nicht gebaut oder bereitgestellt. Wir bieten in der Zwischenzeit keine gefälschte oder defekte Version dieser Tools an.',
    privacy_p3: 'Diese Seite hat derzeit keine Konten, keine Datenbank und kein Tracking — es ist eine statische Werkzeugseite. Sollten später Konten oder eine Premium-Stufe hinzukommen, wird diese Richtlinie neu geschrieben, um die dann tatsächlich erhobenen Daten korrekt zu beschreiben — nicht vorher.',
    footer_tagline: 'Schnelle PDF- und Bildwerkzeuge, die Ihre Dateien respektieren — und Ihnen ehrlich sagen, was echt ist.',
    footer_product: 'Produkt',
    footer_alltools: 'Alle Werkzeuge',
    footer_pricing: 'Preise',
    footer_company: 'Unternehmen',
    footer_privacy: 'Datenschutz',
    footer_copy: '© 2026 DocuFlowPlus. Ehrlich gebaut, Werkzeug für Werkzeug.',
    // Tool Names and Descs
    tool_compress_name: 'PDF komprimieren',
    tool_compress_desc: 'Reduziert die PDF-Dateigröße durch Struktur-Optimierung.',
    tool_merge_name: 'PDF zusammenführen',
    tool_merge_desc: 'Kombiniert mehrere PDF-Dateien in einem Dokument.',
    tool_split_name: 'PDF teilen',
    tool_split_desc: 'Extrahiert jede PDF-Seite als einzelne Datei in ein ZIP.',
    tool_img2pdf_name: 'Bild zu PDF',
    tool_img2pdf_desc: 'Kombiniert ein oder mehrere Bilder in einer PDF-Datei.',
    tool_pdf2img_name: 'PDF zu Bild',
    tool_pdf2img_desc: 'Konvertiert jede PDF-Seite in ein PNG-Bild.',
    tool_imgconv_name: 'Bildkonverter',
    tool_imgconv_desc: 'Konvertiert Bilder zwischen PNG, JPG und WEBP.',
    tool_watermark_name: 'PDF Wasserzeichen',
    tool_watermark_desc: 'Fügt einen diagonalen Wasserzeichentext auf jeder Seite hinzu.',
    tool_pagenum_name: 'Seitenzahlen',
    tool_pagenum_desc: 'Fügt Seitenzahlen im Format „Seite X von N“ am Seitenende hinzu.',
    tool_rotate_name: 'PDF drehen',
    tool_rotate_desc: 'Dreht alle Seiten einer PDF um 90, 180 oder 270 Grad.',
    tool_pdf2word_name: 'PDF zu Word',
    tool_pdf2word_desc: 'Extrahiert Text aus PDF-Dateien in ein editierbares Word-Dokument.',
    tool_word2pdf_name: 'Word zu PDF',
    tool_word2pdf_desc: 'Konvertiert .docx-Dateien in das PDF-Format.'
  },
  pt: {
    nav_tools: 'Ferramentas',
    nav_pricing: 'Preços',
    nav_privacy: 'Privacidade',
    nav_browse: 'Ver ferramentas',
    hero_eyebrow: '9 ferramentas ativas · 100% no seu navegador · verificadas',
    hero_h1: 'Ferramentas de PDF e imagem que <span class="text-brass">realmente funcionam</span> no seu navegador.',
    hero_p: 'Comprima, una, divida, gire, aplique marca d\'água e converta — tudo processado inteiramente no seu dispositivo usando bibliotecas reais de navegador. Sem envios. Sem conta necessária para testar.',
    cta_browse: 'Ver todas as ferramentas',
    cta_pricing: 'Ver preços',
    fact_1: 'ferramentas ativas e verificadas',
    fact_2: 'arquivos que saem do seu dispositivo',
    fact_3: 'ferramentas em breve',
    honesty_title: 'Nota de status honesta:',
    honesty_body: 'cada ferramenta marcada como "Ativa" abaixo usa uma biblioteca real do lado do cliente (pdf-lib, pdf.js, canvas) e foi verificada em relação à API real dessa biblioteca antes de ser construída — nunca presumida. PDF↔Word precisam de processamento no servidor que ainda não construímos, e a proteção por senha de PDF não é possível de forma confiável com as bibliotecas usadas aqui — ambas estão marcadas como "Em breve" em vez de simuladas.',
    tools_eyebrow: 'Ferramentas disponíveis',
    tools_h2: 'As 9 ferramentas',
    tools_p: 'Escolha uma ferramenta para começar. Ferramentas ativas processam seu arquivo aqui mesmo, agora.',
    pricing_eyebrow: 'Preços',
    pricing_h2: 'Preços simples',
    pricing_p: 'Comece grátis. A cobrança Premium ainda não está ativa, então ninguém está sendo cobrado por enquanto.',
    price_free_tier: 'GRÁTIS',
    price_free_1: 'As 9 ferramentas ativas, uso ilimitado',
    price_free_2: 'Processamento genuinamente local',
    price_free_3: 'Não requer cadastro',
    price_free_4: 'Sem limites artificiais de tamanho — apenas a memória do seu navegador importa',
    price_free_btn: 'Começar a usar as ferramentas',
    price_premium_tier: 'PREMIUM',
    price_premium_1: 'Processamento em lote / pasta',
    price_premium_2: 'Reordenar arrastrando',
    price_premium_3: 'Download dos resultados em ZIP',
    price_premium_4: 'Suporte prioritário',
    price_premium_btn: 'Em breve — cobrança ainda não implementada',
    privacy_eyebrow: 'Privacidade',
    privacy_h2: 'O que realmente acontece com seus arquivos',
    privacy_p1: 'Comprimir PDF, Unir PDF, Dividir PDF, Imagem para PDF, PDF para Imagem, Conversor de Imagem, Marca d\'Água, Numeração de Páginas e Girar PDF — essas 9 ferramentas funcionam inteiramente no seu navegador usando bibliotecas de código aberto (pdf-lib, pdf.js e a própria API Canvas do navegador). Seu arquivo é carregado na memória do navegador, processado, e o resultado é oferecido a você como download. Nunca é transmitido a lugar nenhum. Você pode verificar isso abrindo a aba de rede do seu navegador enquanto usa qualquer uma dessas ferramentas.',
    privacy_p2: 'PDF para Word e Word para PDF ainda não estão ativas. Essas conversões normalmente exigem processamento no servidor para funcionar de forma confiável, e ainda não construímos nem implantamos esse backend. Não oferecemos uma versão falsa ou quebrada dessas ferramentas enquanto isso.',
    privacy_p3: 'Esta página atualmente não tem contas, banco de dados nem rastreamento — é uma página estática de ferramentas. Se contas ou um nível premium forem adicionados depois, esta política será reescrita para descrever com precisão os dados reais coletados naquele momento, não antes.',
    footer_tagline: 'Ferramentas rápidas de PDF e imagem que respeitam seus arquivos — e dizem a verdade sobre o que é real.',
    footer_product: 'Produto',
    footer_alltools: 'Todas as ferramentas',
    footer_pricing: 'Preços',
    footer_company: 'Empresa',
    footer_privacy: 'Privacidade',
    footer_copy: '© 2026 DocuFlowPlus. Construído com honestidade, ferramenta por ferramenta.',
    // Tool Names and Descs
    tool_compress_name: 'Comprimir PDF',
    tool_compress_desc: 'Reduz o tamanho de arquivos PDF otimizando a estrutura interna.',
    tool_merge_name: 'Unir PDF',
    tool_merge_desc: 'Combina vários PDFs em um único documento.',
    tool_split_name: 'Dividir PDF',
    tool_split_desc: 'Extrai cada página de um PDF em arquivos separados em um ZIP.',
    tool_img2pdf_name: 'Imagem para PDF',
    tool_img2pdf_desc: 'Combina uma ou mais imagens em um único PDF.',
    tool_pdf2img_name: 'PDF para Imagem',
    tool_pdf2img_desc: 'Converte cada página de um PDF em uma imagem PNG.',
    tool_imgconv_name: 'Conversor de Imagem',
    tool_imgconv_desc: 'Converte imagens entre formatos PNG, JPG e WEBP.',
    tool_watermark_name: 'Marca d\'Água',
    tool_watermark_desc: 'Aplica um texto diagonal de marca d\'água em cada página.',
    tool_pagenum_name: 'Adicionar Números',
    tool_pagenum_desc: 'Adiciona numeração de página no rodapé de todas as páginas.',
    tool_rotate_name: 'Girar PDF',
    tool_rotate_desc: 'Gira todas as páginas de um PDF em 90, 180 ou 270 graus.',
    tool_pdf2word_name: 'PDF para Word',
    tool_pdf2word_desc: 'Extrai o texto do PDF para um documento Word editável.',
    tool_word2pdf_name: 'Word para PDF',
    tool_word2pdf_desc: 'Converte arquivos .docx para o formato PDF.'
  }
};
